Update Google_IT_Automation

diff --git a/Google_IT_Automation b/Google_IT_Automation
--- a/Google_IT_Automation
+++ b/Google_IT_Automation
@@ -794,6 +794,78 @@ $ echo c* (returns all the files in the current directory that start with the le
 Python files with 5 characters in their name:
 $ echo $$$$$.py
 
+$? checks the exit status of commands
+In bash scripting, an exit value of 0 means success.
+We want to check if the /etc/hosts file contains an entry for 127.0.0.1
+grep will return an exit status of 0 when it finds at least one match
+$ cat check_localhost.sh
+#!/bin/bash
+if grep "127.0.0.1" /etc/hosts; then
+        echo "Everything ok"
+else
+        echo "ERROR! 127.0.0.1 is not in /etc/host"
+fi
+$ ./check_localhost.sh
+127.0.0.1       localhost
+Everything ok
+The first line in the output is the one generated by the grep command, by default it prints the lines that match the expression that we give it
+test: command that evaluates the conditions received and exits with zero when they're true and with one when they're false
+-n checks if a string variable is empty or not
+$ if test -n "$PATH"; then echo "Your path is not empty"; fi
+same as:
+$ if [ -n "$PATH"]; then echo "Your path is not empty"; fi
+
+$ cat while.sh
+#!/bin/bash
+n=1
+while [ $n -le 5 ]; do
+        echo "Iteration number $n"
+        ((n+=1))
+done
+checks if variable n is less than or equal to 5
+$ ./while.sh
+Iteration number 1
+Iteration number 2
+Iteration number 3
+Iteration number 4
+Iteration number 5
+
+$ cat random-exit.py
+#!/usr/bin/env python
+import sys
+import random
+value=random.randint(0,3)
+print("Returning: " + str(value))
+sys.exit(value)
+
+#!/bin/bash
+n=0
+command=$1
+while ! $command && [ $n -le 5 ]; do
+        sleep $n
+        ((n=n+1))
+        echo "Retry #$n"
+done;
+
+$1 returns the first command line argument (same as sys.argv[1])
+If the received command fails, we will retry up to 5 times
+
+$ ./retry.sh ./random-exit.py
+Returning: 1
+Retry #1
+Returning: 3
+Retry #2
+Returning: 1
+Retry #3
+Returning: 0
+
+
+
+
+
+
+ 
+
 
 
 
